const randomStarts = [
  [
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(6),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(3, false, false, false, true),
      new Cell(-1),
      new Cell(1, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
      new Cell(3, false, false, true, true),
      new Cell(-1),
      new Cell(1, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(1, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(4, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(5, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(4, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(5, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
      new Cell(7),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(2, false, true, false, false),
      new Cell(2, false, true, true, false),
      new Cell(2, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(8),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(9),
    ],
  ],
];
