const randomStarts = [
  [
    [
      new Cell(-1),
      new Cell(2),
      new Cell(-1),
      new Cell(-1),
      new Cell(1),
      new Cell(1),
      new Cell(1),
      new Cell(1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(2),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(2),
      new Cell(0),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(4),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(4),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0),
      new Cell(-1),
      new Cell(-1),
      new Cell(3),
      new Cell(3),
      new Cell(3),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
  ],
];
