const randomStarts = [
  [
    [
      new Cell(-1),
      new Cell(2, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(1, false, true, false, false),
      new Cell(1, true, true, false, false),
      new Cell(1, true, true, false, false),
      new Cell(1, true, false, false, false),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(2, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(2, false, false, true, false),
      new Cell(0, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(4, false, false, false, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(4, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, true),
      new Cell(-1),
      new Cell(-1),
      new Cell(3, false, true, false, false),
      new Cell(3, true, true, false, false),
      new Cell(3, true, false, false, false),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(0, false, false, true, false),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
    [
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
      new Cell(-1),
    ],
  ],
];
